table Products
	lineageTag: 84536826-6373-4afe-9790-4d62d5c3a0f0
	sourceLineageTag: [SupplyChain].[DimProducts]

	measure 'Average Product Price' = AVERAGE(Products[Price])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Product Metrics
		lineageTag: 92859d6b-73f2-4882-9933-ee5c3cdb606e

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Top Selling Product' = TOPN(1, VALUES(Products[Product]), [Total Products Sold], DESC)
		displayFolder: Product Metrics
		lineageTag: 1016a5eb-7ea6-4d09-bc62-218c4bd70e20

		changedProperty = DisplayFolder

		changedProperty = Name

	column 'Product ID'
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 4e68391f-37c4-4526-b0ca-6fe085e61ee8
		sourceLineageTag: ProductID
		summarizeBy: none
		sourceColumn: ProductID

		changedProperty = IsHidden

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		sourceProviderType: varchar(500)
		displayFolder: Product Details
		lineageTag: 8d462753-83c4-40e1-a92e-553bc27a09d6
		sourceLineageTag: ProductName
		summarizeBy: none
		sourceColumn: ProductName

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

	column 'Category ID'
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: f7e07b05-8523-442b-8755-d636ae08eafe
		sourceLineageTag: CategoryID
		summarizeBy: none
		sourceColumn: CategoryID

		changedProperty = IsHidden

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Department ID'
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 1676d0b7-700a-4c38-9733-7ce43e59e24a
		sourceLineageTag: DepartmentID
		summarizeBy: none
		sourceColumn: DepartmentID

		changedProperty = IsHidden

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Price
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		sourceProviderType: float
		displayFolder: Product Details
		lineageTag: 60b45b9b-b5c7-4087-be0c-ea55c060202a
		sourceLineageTag: Price
		summarizeBy: sum
		sourceColumn: Price

		changedProperty = FormatString

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition Products = entity
		mode: directLake
		source
			entityName: DimProducts
			schemaName: SupplyChain
			expressionSource: DatabaseQuery

	changedProperty = Name

	annotation PBI_ResultType = Table

